### ISSUE TITLE
Presentation is not finished yet

### ISSUE THREAD

**Issue by leletec** [okitec/git-ref#2]
- [x] The slides of the fodp file are not animated.
- [x] The presentation file (fodp) is not complete.
- [x] Not all the resources are added.
- [x] Check for formating errors.
- [x] Update README.md @okitec

**Comment by okitec** [comment]
I see no need to use animated slides; better use an entirely new slide and have less text on each.

**Comment by leletec** [comment]
Yeah but I don't really wont to use a new slide for each line of text...

**Comment by okitec** [comment]
What resources do you mean in the third task?

**Comment by leletec** [comment]
Like sources of pictures ... something like that
